{"stability":{"stable since":"1.0.0"},"apiName":"std::sync::TryLockError","apiType":"enum","apiDocumentation":{"apiDescription":["An enumeration of possible errors associated with a TryLockResult which can occur while trying to acquire a lock, from the try_lock method on a Mutex or the try_read and try_write methods on an RwLock."]},"enum variants":["Poisoned(PoisonError<T>)","The lock could not be acquired because another thread failed while holding\nthe lock.\n","WouldBlock","The lock could not be acquired at this time because the operation would\notherwise block.\n"],"trait implementations":[{"name":"impl<T> std::convert::From<std::sync::PoisonError<T>> for std::sync::TryLockError<T>","stable since":"1.0.0"},{"name":"impl<T> std::fmt::Debug for std::sync::TryLockError<T>","stable since":"1.0.0"},{"name":"impl<T> std::fmt::Display for std::sync::TryLockError<T>","stable since":"1.0.0"},{"name":"impl<T> std::error::Error for std::sync::TryLockError<T>","stable since":"1.0.0"},{"name":"impl<T> std::marker::Send for std::sync::TryLockError<T> where T: std::marker::Send","stable since":"1.0.0"},{"name":"impl<T> std::marker::Sync for std::sync::TryLockError<T> where T: std::marker::Sync","stable since":"1.0.0"}]}